#/DDPosition 70.
#/run/reinitializeGeometry
#/run/beamOn 1 
#/control/execute vis.mac

#/run/beamOn 1000

/DDPos/DDPosition 70.
/DDPos2/DDPosition 70.
/run/reinitializeGeometry
/run/beamOn 1000 
/control/execute vis.mac

/DDPos/DDPosition 40.
/DDPos2/DDPosition 40.
/run/reinitializeGeometry
/run/beamOn 1000 
/control/execute vis.mac

/DDSize/DDSize 10.
/DDSize2/DDSize 10.
/run/reinitializeGeometry
/run/beamOn 1000 
/control/execute vis.mac

/DDSize/DDSize 4.75
/DDSize2/DDSize 4.75
/run/reinitializeGeometry
/run/beamOn 1000 
/control/execute vis.mac

/DetectorsOnOrOff/ID 1
/DetectorsOnOrOff2/ID 1
/run/reinitializeGeometry
/run/beamOn 1000 
/control/execute vis.mac

/DetectorsOnOrOff/DD 1
/DetectorsOnOrOff2/DD 1
/run/reinitializeGeometry
/run/beamOn 1000 
/control/execute vis.mac
